name: toDoList

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    name: Development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Build Docker image
        run: docker build -t todolist-app .
      - name: Check Docker build status
        run: echo "::set-output name=DOCKER_BUILD_STATUS::$(echo $?)"
      - name: Check if Docker build succeeded
        run: exit $DOCKER_BUILD_STATUS
        if: ${{ success() }}
